export type OpportunityType = "Private Trading" | "Company Investment";
export type Sector = "Technology" | "Fintech" | "Gaming" | "Health";
export type Region = "AU" | "US" | "China" | "Global";

export type Opportunity = {
  name: string;
  initials: string;
  /** Clearbit domain (e.g. "openai.com") OR a local path (e.g. "/logos/anahad.png") */
  logo?: string;
  /** Background colour for the logo circle when the favicon has transparency */
  logoBg?: string;
  type: OpportunityType;
  isUnicorn?: boolean;
  sector: Sector;
  region: Region;
  blurb: string;
  href: string;
};

export const opportunities: Opportunity[] = [
  {
    name: "Anthropic",
    initials: "AN",
    logo: "anthropic.com",
    logoBg: "#F0EEE6",
    type: "Private Trading",
    isUnicorn: true,
    sector: "Technology",
    region: "US",
    blurb: "AI safety company behind Claude — a frontier large-language-model assistant for businesses and developers.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Neuralink",
    initials: "NL",
    logo: "neuralink.com",
    logoBg: "#ffffff",
    type: "Private Trading",
    isUnicorn: true,
    sector: "Health",
    region: "US",
    blurb: "Brain-computer interface company developing implantable neural devices to restore and enhance human capability.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Anduril",
    initials: "AD",
    logo: "anduril.com",
    logoBg: "#ffffff",
    type: "Private Trading",
    isUnicorn: true,
    sector: "Technology",
    region: "US",
    blurb: "Defence technology company designing autonomous systems and AI software for military and security operations.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Kalshi",
    initials: "KL",
    logo: "kalshi.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "CFTC-regulated prediction-market exchange where traders can take positions on real-world event outcomes.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "OpenAI",
    initials: "OA",
    logo: "openai.com",
    type: "Private Trading",
    sector: "Technology",
    region: "US",
    blurb: "AI research and deployment lab behind ChatGPT and the GPT model family.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "ByteDance",
    initials: "BD",
    logo: "tiktok.com",
    logoBg: "#ffffff",
    type: "Private Trading",
    sector: "Technology",
    region: "China",
    blurb: "Technology group behind TikTok, Douyin and a global suite of consumer applications.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Lambda",
    initials: "LM",
    logo: "lambdalabs.com",
    type: "Private Trading",
    sector: "Technology",
    region: "US",
    blurb: "AI cloud infrastructure provider offering GPU clusters and on-demand compute for training and deploying large-scale models.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Plaid",
    initials: "PL",
    logo: "plaid.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Financial data infrastructure connecting consumer apps to banks across North America and Europe.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Airtable",
    initials: "AT",
    logo: "airtable.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Collaborative platform that combines the power of a database with the simplicity of a spreadsheet.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Kraken",
    initials: "KR",
    logo: "kraken.com",
    type: "Private Trading",
    isUnicorn: true,
    sector: "Fintech",
    region: "US",
    blurb: "Leading global cryptocurrency exchange known for institutional-grade security and broad asset coverage.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "DriveWealth",
    initials: "DW",
    logo: "drivewealth.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Brokerage-as-a-service platform powering fractional investing for global fintechs.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Miro",
    initials: "MR",
    logo: "miro.com",
    type: "Private Trading",
    sector: "Technology",
    region: "US",
    blurb: "Collaborative online whiteboard for distributed teams working through complex visual problems.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Patreon",
    initials: "PT",
    logo: "patreon.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Membership platform helping artists, writers, and creators earn directly from their fans.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Epic Games",
    initials: "EG",
    logo: "epicgames.com",
    type: "Private Trading",
    sector: "Gaming",
    region: "US",
    blurb: "Maker of Fortnite and Unreal Engine — one of the largest privately-held games and 3D-tooling businesses.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Chime",
    initials: "CH",
    logo: "chime.com",
    logoBg: "#00D54B",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Fee-free mobile banking covering checking, savings, and credit-builder accounts.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Ripple",
    initials: "RP",
    logo: "ripple.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Blockchain infrastructure for cross-border payments and institutional digital-asset settlement.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Scale AI",
    initials: "SA",
    logo: "scale.com",
    logoBg: "#ffffff",
    type: "Private Trading",
    sector: "Technology",
    region: "US",
    blurb: "Data and AI infrastructure for training the next generation of foundation models.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "Wealthfront",
    initials: "WF",
    logo: "wealthfront.com",
    type: "Private Trading",
    sector: "Fintech",
    region: "US",
    blurb: "Digital wealth manager combining automated investing with high-yield cash strategies.",
    href: "https://app.floatx.com/signup",
  },
  {
    name: "ANAHAD",
    initials: "AH",
    type: "Company Investment",
    sector: "Fintech",
    region: "AU",
    blurb: "Innovative pharmacy supply-chain platform raising primary capital through FloatX.",
    href: "/investments/company-investment",
  },
  {
    name: "ArthroLase",
    initials: "AL",
    type: "Company Investment",
    sector: "Health",
    region: "AU",
    blurb: "Intelligent joint-resurfacing technology company raising primary capital through FloatX.",
    href: "/investments/company-investment",
  },
  {
    name: "Deep Touch",
    initials: "DT",
    type: "Company Investment",
    sector: "Fintech",
    region: "AU",
    blurb: "Australian deep-tech R&D company raising primary capital through FloatX.",
    href: "/investments/company-investment",
  },
  {
    name: "Oxygen Health Clinics",
    initials: "OX",
    type: "Company Investment",
    sector: "Health",
    region: "AU",
    blurb: "Accessible health-services group raising primary capital through FloatX.",
    href: "/investments/company-investment",
  },
];

export const regionLabel: Record<Region, string> = {
  AU: "AU",
  US: "US",
  Global: "Global",
  China: "CN",
};

export const sectors: Sector[] = ["Technology", "Fintech", "Gaming", "Health"];
